version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget
