swagger:
	curl -L -o swagger.yaml http://localhost:3001/swagger/yaml
	./lib/swagger-coverage-commandline/bin/swagger-coverage-commandline -s swagger.yaml -i ./target/swagger-coverage-output -c swagger-coverage-config.json

