name: Backend Tests
on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  unit-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        id: jest
        run: npm run test
      - name: Upload backend html report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: backend-unit-test-report
          path: backend/reports/html-report-unit
          retention-days: 1

  deploy:
    permissions:
      pages: write
      id-token: write
    needs: unit-test
    if: always()
    uses: ./.github/workflows/deploy-reports.yml
