name: Pact Tests
on:
  workflow_dispatch:

jobs:
  pact-consumer-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run pact tests
        id: pact-consumer
        run: npm run test:pact
      - name: Upload pact consumer report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: pact-consumer-report
          path: frontend/reports/pact-consumer-report
          retention-days: 1
      - name: Upload pacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: pacts
          path: pacts
          retention-days: 1

  pact-provider-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: pact-consumer-test
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: actions/download-artifact@v4
        with:
          name: pacts
          path: pacts
      - name: Install dependencies
        run: npm ci
      - name: Run pact tests
        id: pact-provider
        run: npm run test:pact
        continue-on-error: true
      - name: Upload pact provider report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: pact-provider-report
          path: backend/reports/pact-provider-report
          retention-days: 1

  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    needs:
      - pact-consumer-test
      - pact-provider-test
    if: always()
    uses: ./.github/workflows/deploy-reports.yml
