name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Select the tag to run'
        type: choice
        options:
          - all
          - smoke
          - regress

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
      options: --user 1001
    defaults:
      run:
        working-directory: ./tests/playwright
    environment:
      name: html-report
      url: ${{ needs.deploy-reports.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        id: playwright
        run: npx playwright test
      - name: Upload Playwright html report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-html-report
          path: tests/playwright/reports/html-report
          retention-days: 1
      - name: Upload Playwright monocart report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-monocart-report
          path: tests/playwright/reports/monocart-report
          retention-days: 1
      - name: Add playwright test results summary
        id: playwright-summary
        uses: viktorhreptovich/playwright-summary-action@main
        if: always()
        with:
          file-path: tests/playwright/reports/json/results.json
      - name: Telegram notification
        uses: cbrgm/telegram-github-action@v1.2.2
        if: always()
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          parse-mode: markdown
          disable-web-page-preview: true
          message: |
            🚀 Playwright tests finished
            Status: ${{ steps.playwright.conclusion}} 🤬
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Details: 
            Start time: ${{ steps.playwright-summary.outputs.starttime}}
            Duration: ${{ steps.playwright-summary.outputs.duration}}
            🟢 Passed   ${{ steps.playwright-summary.outputs.passed}}
            🔴 Failed   ${{ steps.playwright-summary.outputs.failed}}
            ⚪ Skipped  ${{ steps.playwright-summary.outputs.skipped}}
            🟠 Flaky    ${{ steps.playwright-summary.outputs.flaky}}
            
  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: playwright-test
    if: always()
    uses: ./.github/workflows/deploy-reports.yml
