name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Select the tag to run'
        type: choice
        options:
          - all
          - smoke
          - regress

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
      options: --user 1001
    defaults:
      run:
        working-directory: ./tests/playwright
    environment:
      name: html-report
      url: ${{ needs.deploy-reports.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload Playwright html report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-html-report
          path: tests/playwright/reports/html-report
          retention-days: 1
      - name: Upload Playwright monocart report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-monocart-report
          path: tests/playwright/reports/monocart-report
          retention-days: 1

  deploy:
    permissions:
      pages: write
      id-token: write
    needs: playwright-test
    uses: ./.github/workflows/deploy-reports.yml
